apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: neonoble-ramp
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - {{ .Values.host }}
      secretName: {{ .Values.tlsSecretName }}
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: neonoble-ramp
                port:
                  name: http
