apiVersion: v1
kind: Secret
metadata:
  name: neonoble-ramp-secrets
  namespace: neonoble-ramp
type: Opaque
stringData:
  DATABASE_URL: "postgresql://replace:replace@postgres:5432/neonoble_ramp"
  DATABASE_REPLICA_URL: ""
  REDIS_URL: "redis://redis:6379"
  TRANSAK_API_KEY: ""
  NEXT_PUBLIC_TRANSAK_API_KEY: ""
  TRANSAK_ACCESS_TOKEN: ""
  TRANSAK_API_SECRET: ""
  TRANSAK_WEBHOOK_SECRET: ""
  NEXT_PUBLIC_NENO_TOKEN_ADDRESS: ""
  SENTRY_DSN: ""
  NEXT_PUBLIC_SENTRY_DSN: ""
  TRANSAK_WEBHOOK_IP_ALLOWLIST: ""
  RECONCILIATION_ADMIN_TOKEN: ""
  RISK_BLOCKED_WALLETS: ""
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "http://otel-collector:4318/v1/traces"
