apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
spec:
  selector:
    app: {{ .Release.Name }}-api
  ports:
    - name: http
      port: {{ .Values.api.port }}
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-event-stream
spec:
  clusterIP: None
  selector:
    app: {{ .Release.Name }}-event-stream
  ports:
    - name: replication
      port: 9092
      targetPort: http
