apiVersion: apps/v1
kind: Deployment
metadata:
  name: metaswap-core
  namespace: metaswap
spec:
  replicas: 5
  selector:
    matchLabels:
      app: metaswap-core
  template:
    metadata:
      labels:
        app: metaswap-core
    spec:
      priorityClassName: metaswap-critical
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: core
          image: metaswap-v3-core:1.0.6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: metaswap-production-secrets
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: "2"
              memory: 2Gi
